--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AraaCuteUwU/DiscordWebhookAPI
build-by-default: true
branches:
- master
projects:
  DiscordWebhookAPI:
    path: ""
    model: virion
    type: library
...
